# Generated by Django 6.1 on 2026-08-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='name',
        ),
    ]
