# Generated by Django 6.1 on 2026-08-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WS_APP', '0005_chatroom_created_by_chatroom_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='pin',
            field=models.CharField(max_length=4),
        ),
    ]
